kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.0
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: UDP
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        protocol: UDP
      - containerPort: 31080
        hostPort: 31080
        protocol: TCP
      - containerPort: 31080
        hostPort: 31080
        protocol: UDP
      - containerPort: 31443
        hostPort: 31443
        protocol: TCP
      - containerPort: 31443
        hostPort: 31443
        protocol: UDP
