apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

configMapGenerator:
  - name: config
    envs:
      - .env

secretGenerator:
  - name: secret
    envs:
      - .env.local
