apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../resources
  - routes.yaml

configMapGenerator:
  - name: config
    envs:
      - .env

secretGenerator:
  - name: secret
    envs:
      - .env.local
