apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webapp-template
spec:
  parentRefs:
    - kind: Gateway
      name: dev-gateway
      namespace: nginx-gateway
  rules:
    - matches:
      backendRefs:
        - name: webapp-template
          port: 80
