---
- name: Setup Gateway API
  hosts: localhost

  tasks:
    - name: Create Gateway API CRD
      kubernetes.core.k8s:
        src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

    - name: Install NGINX Gateway Fabric Helm Chart for development
      kubernetes.core.helm:
        name: dev-gateway
        namespace: dev-gateway
        chart_ref: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
        atomic: true
        create_namespace: true
        wait: true
        values: "{{ lookup('file', '../resources/values/dev-gateway.yaml') | from_yaml }}"

    - name: Install NGINX Gateway Fabric Helm Chart for production
      kubernetes.core.helm:
        name: production-gateway
        namespace: production-gateway
        chart_ref: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
        atomic: true
        create_namespace: true
        wait: true
        values: "{{ lookup('file', '../resources/values/production-gateway.yaml') | from_yaml }}"

    - name: Create Issuer & Certificate
      kubernetes.core.k8s:
        namespace: default
        src: ../resources/certificate.yaml

    - name: Create & Expose the Gateway
      kubernetes.core.k8s:
        namespace: default
        src: ../resources/gateway.yaml

    - name: Add label to default namespace to allow access to the gateway
      kubernetes.core.k8s:
        name: default
        kind: Namespace
        merge_type:
          - strategic-merge
        definition:
          metadata:
            labels:
              dev-gateway-access: "true"

    - name: Create Cloudflare API Token Secret
      kubernetes.core.k8s:
        name: cloudflare-api-token
        namespace: production-gateway
        definition:
          kind: Secret
          type: Opaque
          data:
            api-token: "{{ cloudflare_api_token | b64encode }}"

    - name: Add label to production-gateway namespace to allow access to the gateway
      kubernetes.core.k8s:
        name: production-gateway
        kind: Namespace
        merge_type:
          - strategic-merge
        definition:
          metadata:
            labels:
              production-gateway-access: "true"
